# pandas

In [1]:
# def : pandas is a open sourse library  designed for data manipulation and Analysis.
# pandas is designed over the Numpy.

# impotatnt list of operation in Pandas

1. data structure creation (series(1D array),dataframe(2D array))
2. data input and output (csv,excel,sql,json)
3. understading the data set (head,tail,dtype,.....)
4. data flitering and indexing (loc,iloc,where()....)
5. handling of missing values(NaN/Null)
6. removing duplicate values
7. handling inconsistant data
8. data tranformation using apply() and map()
9. Aggregation and grouping
10. Time series operation
11. basic data visualization

# importing and installation of pandas

In [2]:
# 'pip install pandas' this command can create with old numpy version
# 'conda install pandas' this command will update numpy also with pandas. so no issue.
import pandas as  pd

In [3]:
pd.__version__

'2.3.3'

# 1. data structure creation (series(1D array),dataframe(2D array))

### series (1D array)

In [4]:
# create series
ser1 =pd.Series()
print(ser1)

Series([], dtype: object)

In [5]:
# conver list to Series 
list1 = [10,20,30,40,50]
ser2 = pd.Series(list1)
print(ser2)
print(type(ser2))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>

In [6]:
# conver list to Series 
list1 = [10,20,30,40,50,'hello']
ser2 = pd.Series(list1)
print(ser2)
print(type(ser2))
# in pandas strings are represented as object
# imp: in series, all elements have  the same datatype

0       10
1       20
2       30
3       40
4       50
5    hello
dtype: object
<class 'pandas.core.series.Series'>

In [7]:
# example-2: convert tuple to Series
data = (10,20,30,50)
ser3=pd.Series(data)
print(ser3)
print(type(ser3))
print(ser3[2])

# in pandas series direct negative indexing not allowed.

0    10
1    20
2    30
3    50
dtype: int64
<class 'pandas.core.series.Series'>
30

In [8]:
# set cannot be converted to pandas series
# set is unordered and series is ordered, so no conversation
data = {10,20,30,50}
ser3=pd.Series(data)
print(ser3)

TypeError: 'set' type is unordered

In [9]:
# convert the numpy array into series
import numpy as np
arr1 = np.array([10,20,30,40,50])
ser4 = pd.Series(arr1,index=['a','b','c','d','e'])
print(arr1,type(arr1))
print(ser4,type(ser4))
print(ser4['a'])

[10 20 30 40 50] <class 'numpy.ndarray'>
a    10
b    20
c    30
d    40
e    50
dtype: int64 <class 'pandas.core.series.Series'>
10

In [10]:
# update operation on series
ser3[3]=450
# insert new value
ser3[5] = 550
ser3['a'] =650
ser3[60] =750
ser3[1.2] = 950

In [11]:
print(ser3)

0       10
1       20
2       30
3      450
5      550
a      650
60     750
1.2    950
dtype: int64

In [12]:
# delete element form series
ser2 = ser2.drop(1)
ser2

0       10
2       30
3       40
4       50
5    hello
dtype: object

DAY-2

# dataframe(2D array)

In [13]:
# DATA frame is a 2d array,store data in form of matrix.

### creating data frame

In [14]:
import pandas as pd

In [15]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [19]:
# converting list to dataframe
fruits_list = ['aratipandu','mamadipandu','kamalapandu','drakshapandu']
df=pd.DataFrame(fruits_list,columns = ['fruit_name'])
df

     fruit_name
0    aratipandu
1   mamadipandu
2   kamalapandu
3  drakshapandu

In [20]:
# converting 2D list to DataFrame
fruits_list = [['aratipandu',40],['mamadipandu',100],['kamalapandu',20],['drakshapandu',480]]
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price'])
df

     fruit_name  price
0    aratipandu     40
1   mamadipandu    100
2   kamalapandu     20
3  drakshapandu    480

In [30]:
fruits_list = [('aratipandu',40),('mamadipandu',100),('kamalapandu',20),('drakshapandu',480)]
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price'])
df

     fruit_name  price
0   kamalapandu     20
1    aratipandu     40
2  drakshapandu    480
3   mamadipandu    100

In [31]:
# converting 2D list to DataFrame using 3 columns
fruits_list = [['aratipandu',40,10],['mamadipandu',100,90],['kamalapandu',20,5],['drakshapandu',480,120]]
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price','dicount'])
df

     fruit_name  price  dicount
0    aratipandu     40       10
1   mamadipandu    100       90
2   kamalapandu     20        5
3  drakshapandu    480      120

In [33]:
# converting 2D list to DataFrame using 3 columns
fruits_list = {('aratipandu',40,10),('mamadipandu',100,90),('kamalapandu',20,5),('drakshapandu',480,120)}
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price','dicount'])
df

     fruit_name  price  dicount
0   mamadipandu    100       90
1   kamalapandu     20        5
2  drakshapandu    480      120
3    aratipandu     40       10

In [36]:
# creating DataFram from set of tuples
fruits_list = {('aratipandu',40,10),('mamadipandu',100,90),('kamalapandu',20,5),('drakshapandu',480,120)}
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price','dicount'])
df

     fruit_name  price  dicount
0   mamadipandu    100       90
1   kamalapandu     20        5
2  drakshapandu    480      120
3    aratipandu     40       10

In [37]:
# creating DataFram from set of set we cannot create because set is mutable, list is also mutable
# in set we cannot store the mutable items.
# in set only immutable items can store
fruits_list = {{'aratipandu',40,10},{'mamadipandu',100,90},{'kamalapandu',20,5},{'drakshapandu',480,120}}
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price','dicount'])
df

TypeError: unhashable type: 'set'

In [40]:
# creating data frame from dictionary
st_data = {'name':['shiva','niranjan','harish','cherry','sai'],'salary':[40,50,60,15,25],'stu_time':[6,4,5,1,3]}
df= pd.DataFrame(st_data)
df

       name  salary  stu_time
0     shiva      40         6
1  niranjan      50         4
2    harish      60         5
3    cherry      15         1
4       sai      25         3

## 2. data input and output (csv,excel,sql,json)

In [49]:
# importing data from csv file 
import os
os.getcwd()
df_csv = pd.read_csv("CSV_data.csv")
df_csv

       Name   Age         Profession  Salary                    Favorite Quote
0      John  25.0  Software Engineer   80000            Keep calm and code on!
1     Alice   NaN             Doctor  120000           Trust me, I'm a doctor!
2     Rocky   NaN              Boxer   50000                 Eye of the tiger!
3  Sherlock  40.0          Detective  150000  It's elementary, my dear Watson.
4  Mr. Bean  50.0           Comedian   10000                   Why so serious?
5  Mr. Bean  50.0           Comedian   10000                   Why so serious?

In [52]:
# import excel file as a DataFrame
df_excel=pd.read_excel("Excel_data.xlsx")
df_excel

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [53]:
# export the  data back to csv  and excel file
df_csv.to_excel("Da22_excel.xlsx",index=False)
df_excel.to_csv("Da22_CSV.csv",index=False)