# pandas

In [1]:
# def : pandas is a open sourse library  designed for data manipulation and Analysis.
# pandas is designed over the Numpy.

# impotatnt list of operation in Pandas

1. data structure creation (series(1D array),dataframe(2D array))
2. data input and output (csv,excel,sql,json)
3. understading the data set (head,tail,dtype,.....)
4. data flitering and indexing (loc,iloc,where()....)
5. handling of missing values(NaN/Null)
6. removing duplicate values
7. handling inconsistant data
8. data tranformation using apply() and map()
9. Aggregation and grouping
10. Time series operation
11. basic data visualization

# importing and installation of pandas

In [2]:
# 'pip install pandas' this command can create with old numpy version
# 'conda install pandas' this command will update numpy also with pandas. so no issue.
import pandas as  pd

In [3]:
pd.__version__

'2.3.3'

# 1. data structure creation (series(1D array),dataframe(2D array))

### series (1D array)

In [4]:
# create series
ser1 =pd.Series()
print(ser1)

Series([], dtype: object)

In [5]:
# conver list to Series 
list1 = [10,20,30,40,50]
ser2 = pd.Series(list1)
print(ser2)
print(type(ser2))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>

In [6]:
# conver list to Series 
list1 = [10,20,30,40,50,'hello']
ser2 = pd.Series(list1)
print(ser2)
print(type(ser2))
# in pandas strings are represented as object
# imp: in series, all elements have  the same datatype

0       10
1       20
2       30
3       40
4       50
5    hello
dtype: object
<class 'pandas.core.series.Series'>

In [7]:
# example-2: convert tuple to Series
data = (10,20,30,50)
ser3=pd.Series(data)
print(ser3)
print(type(ser3))
print(ser3[2])

# in pandas series direct negative indexing not allowed.

0    10
1    20
2    30
3    50
dtype: int64
<class 'pandas.core.series.Series'>
30

# set cannot be converted to pandas series
# set is unordered and series is ordered, so no conversation
data = {10,20,30,50}
ser3=pd.Series(data)
print(ser3)

In [8]:
# convert the numpy array into series
import numpy as np
arr1 = np.array([10,20,30,40,50])
ser4 = pd.Series(arr1,index=['a','b','c','d','e'])
print(arr1,type(arr1))
print(ser4,type(ser4))
print(ser4['a'])

[10 20 30 40 50] <class 'numpy.ndarray'>
a    10
b    20
c    30
d    40
e    50
dtype: int64 <class 'pandas.core.series.Series'>
10

In [9]:
# update operation on series
ser3[3]=450
# insert new value
ser3[5] = 550
ser3['a'] =650
ser3[60] =750
ser3[1.2] = 950

In [10]:
print(ser3)

0       10
1       20
2       30
3      450
5      550
a      650
60     750
1.2    950
dtype: int64

In [11]:
# delete element form series
ser2 = ser2.drop(1)
ser2

0       10
2       30
3       40
4       50
5    hello
dtype: object

DAY-2

# dataframe(2D array)

In [12]:
# DATA frame is a 2d array,store data in form of matrix.

### creating data frame

In [13]:
import pandas as pd

In [14]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [15]:
# converting list to dataframe
fruits_list = ['aratipandu','mamadipandu','kamalapandu','drakshapandu']
df=pd.DataFrame(fruits_list,columns = ['fruit_name'])
df

     fruit_name
0    aratipandu
1   mamadipandu
2   kamalapandu
3  drakshapandu

In [16]:
# converting 2D list to DataFrame
fruits_list = [['aratipandu',40],['mamadipandu',100],['kamalapandu',20],['drakshapandu',480]]
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price'])
df

     fruit_name  price
0    aratipandu     40
1   mamadipandu    100
2   kamalapandu     20
3  drakshapandu    480

In [17]:
fruits_list = [('aratipandu',40),('mamadipandu',100),('kamalapandu',20),('drakshapandu',480)]
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price'])
df

     fruit_name  price
0    aratipandu     40
1   mamadipandu    100
2   kamalapandu     20
3  drakshapandu    480

In [18]:
# converting 2D list to DataFrame using 3 columns
fruits_list = [['aratipandu',40,10],['mamadipandu',100,90],['kamalapandu',20,5],['drakshapandu',480,120]]
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price','dicount'])
df

     fruit_name  price  dicount
0    aratipandu     40       10
1   mamadipandu    100       90
2   kamalapandu     20        5
3  drakshapandu    480      120

In [19]:
# converting 2D list to DataFrame using 3 columns
fruits_list = {('aratipandu',40,10),('mamadipandu',100,90),('kamalapandu',20,5),('drakshapandu',480,120)}
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price','dicount'])
df

     fruit_name  price  dicount
0   mamadipandu    100       90
1   kamalapandu     20        5
2  drakshapandu    480      120
3    aratipandu     40       10

In [20]:
# creating DataFram from set of tuples
fruits_list = {('aratipandu',40,10),('mamadipandu',100,90),('kamalapandu',20,5),('drakshapandu',480,120)}
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price','dicount'])
df

     fruit_name  price  dicount
0   mamadipandu    100       90
1   kamalapandu     20        5
2  drakshapandu    480      120
3    aratipandu     40       10

# creating DataFram from set of set we cannot create because set is mutable, list is also mutable
# in set we cannot store the mutable items.
# in set only immutable items can store
fruits_list = {{'aratipandu',40,10},{'mamadipandu',100,90},{'kamalapandu',20,5},{'drakshapandu',480,120}}
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price','dicount'])
df

In [21]:
# creating data frame from dictionary
st_data = {'name':['shiva','niranjan','harish','cherry','sai'],'salary':[40,50,60,15,25],'stu_time':[6,4,5,1,3]}
df= pd.DataFrame(st_data)
df

       name  salary  stu_time
0     shiva      40         6
1  niranjan      50         4
2    harish      60         5
3    cherry      15         1
4       sai      25         3

## 2. data input and output (csv,excel,sql,json)

In [22]:
# importing data from csv file 
import os
os.getcwd()
df_csv = pd.read_csv("CSV_data.csv")
df_csv

       Name   Age         Profession  Salary                    Favorite Quote
0      John  25.0  Software Engineer   80000            Keep calm and code on!
1     Alice   NaN             Doctor  120000           Trust me, I'm a doctor!
2     Rocky   NaN              Boxer   50000                 Eye of the tiger!
3  Sherlock  40.0          Detective  150000  It's elementary, my dear Watson.
4  Mr. Bean  50.0           Comedian   10000                   Why so serious?
5  Mr. Bean  50.0           Comedian   10000                   Why so serious?

In [23]:
# import excel file as a DataFrame
df_excel=pd.read_excel("Excel_data.xlsx")
df_excel

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [24]:
# export the  data back to csv  and excel file
df_csv.to_excel("Da22_excel.xlsx",index=False)
df_excel.to_csv("Da22_CSV.csv",index=False)

day-3

In [26]:
df_excel

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [27]:
# reading and writing inn a sql
import sqlite3
# creating a database if it don't exist
conn = sqlite3.connect("shiva_da22.db")

In [28]:
# creating a table and strating the dataframe data inside it
df_excel.to_sql("prof_table",conn,if_exists='replace')

500

In [29]:
# reading the data from sql table to df
df =pd.read_sql('select * from prof_table',conn)
df

,index,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,0,1,olivia,23.0,Teacher,184518,0
1,1,2,sophia,20.0,Boxer,119572,2
2,2,3,jake,38.0,Scientist,174897,1
3,3,4,Rocky,56.0,Chef,117920,2
4,4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...,...
495,495,496,John,45.0,Boxer,137929,0
496,496,497,Sherlock,46.0,Boxer,39870,6
497,497,498,Sherlock,47.0,Detective,165951,5
498,498,499,Olivia,55.0,Comedian,192618,5
499,499,500,Sherlock,59.0,Software Engineer,194886,28

In [30]:
# impoting data from JSON file 
df_json = pd.read_json('json_data.json')
df_json

,order_id,customer_name,food_item,delivery_boy,rating,delivery_time_min
0,101,Ramu,Idli Burger,Speed Shankar,5,15
1,102,Priya,Dosa Pizza,Late Laxman,2,60
2,103,Dinesh,Paneer Sambar,Turbo Thambi,4,25
3,104,Lachu,Mango Maggi,Round Robin,1,90
4,105,Meena,Coconut Coffee,Careless Kannan,3,40

In [31]:
# exporting data from dataframe to json file 
df_json.to_json('food_data.json')

### 3. understading the data set (head,tail,dtype,.....)

In [32]:
# view the data with head(),tail() functions
# head(x) function is used to accessing top x records
# head() by default shows the 5 records
df_excel.head(10)

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1
5   4      Rocky  56.0         Chef  117920                        3
6   4      Rocky  56.0         Chef  117920                       11
7   4      Rocky  56.0         Chef  117920                        2
8   4      Rocky  56.0         Chef  117920                        2
9   4      Rocky  56.0         Chef  117920                        3

In [33]:
# tail(x) function is used to accessing bottom x records
# tail() by default shows the 5 records
df_excel.tail(10)

      ID      Name   Age         Profession  salary  Marriage_proposal_count
490  491      John  57.0              Pilot  154180                        0
491  492      Emma  34.0             Artist  145412                        1
492  493      John  55.0             Artist   57720                        2
493  494    Sophia  39.0             Doctor  174500                        0
494  495     Rocky  27.0             Doctor   46975                        0
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

In [34]:
df_excel.shape

(500, 6)

In [35]:
# shows the single column
df_excel['Name']

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

In [36]:
df_excel.Name

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

In [37]:
df_excel['Profession']

0                Teacher
1                  Boxer
2              Scientist
3                   Chef
4                   Chef
             ...
495                Boxer
496                Boxer
497            Detective
498             Comedian
499    Software Engineer
Name: Profession, Length: 500, dtype: object

In [38]:
df_excel[['Name','Profession']]

          Name         Profession
0       olivia            Teacher
1    sophia                 Boxer
2         jake          Scientist
3        Rocky               Chef
4        Rocky               Chef
..         ...                ...
495       John              Boxer
496   Sherlock              Boxer
497   Sherlock          Detective
498     Olivia           Comedian
499   Sherlock  Software Engineer

[500 rows x 2 columns]

In [39]:
# printing multiple columns
df_excel[['Name','Profession','salary']]

          Name         Profession  salary
0       olivia            Teacher  184518
1    sophia                 Boxer  119572
2         jake          Scientist  174897
3        Rocky               Chef  117920
4        Rocky               Chef  117920
..         ...                ...     ...
495       John              Boxer  137929
496   Sherlock              Boxer   39870
497   Sherlock          Detective  165951
498     Olivia           Comedian  192618
499   Sherlock  Software Engineer  194886

[500 rows x 3 columns]

In [40]:
df_rename=df_excel.rename(columns ={'Name':'peru','Profession':'Vruthi'})
df_rename

      ID       peru   Age             Vruthi  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [41]:
# print all the column names 
df_rename.columns

Index(['ID', 'peru', 'Age', 'Vruthi', 'salary', 'Marriage_proposal_count'], dtype='object')

### creating new column in the dataframe

In [42]:
#  here rank() function is a pandas function
# rank() function is giving rank-1 to minmum salary and higher rank value to higher salary
df_excel['rank'] = df_excel['salary'].rank(ascending =False)
df_excel.sort_values('rank')

# sort_values() is used for sorting  the dataframe based upon a column values

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank
436,437,Sherlock,52.0,Boxer,199529,3,1.0
65,66,Emma,57.0,Pilot,199317,1,2.0
132,133,Rocky,31.0,Doctor,198978,8,3.0
167,168,Mr. Bean,44.0,Comedian,198847,14,4.0
474,475,Sophia,30.0,Doctor,198653,1,5.0
...,...,...,...,...,...,...,...
284,285,Jake,46.0,Detective,30971,1,496.0
329,330,Sherlock,40.0,Scientist,30905,0,497.0
398,399,Rocky,25.0,Scientist,30659,5,498.0
90,91,Rocky,43.0,Software Engineer,30407,10,499.0
213,214,Sherlock,21.0,Chef,30164,2,500.0

In [43]:
# droping the column
# axis =1 : delete the column
# axis =0 : delete the row
df_excel=df_excel.drop(['rank'],axis=1)
df_excel

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

DAY-4

### Replace a value in dataframe

In [45]:
df=df_excel
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [47]:
# repalce all the olivia in name column with cherry
df['Name'] = df.Name.replace('olivia','cherry')
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     cherry  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [50]:
# replacing multiple values
df['Name'] = df.Name.replace({'cherry':'shiva','Rocky':'vedhu'})

# replacing values from multiple columns together
# inplace = true : to perform the task without taking extra space  

df= df.replace({'shiva':'AA','Teacher':'hero'})   # or df.replace({'shiva':'AA','Teacher':'hero'}, inplace  = True)
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1         AA  23.0               hero  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      vedhu  56.0               Chef  117920                        2
4      4      vedhu  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [52]:
# dtypes are used to check the datatype of all the columns
# in pandas, strings are represented with object
df.dtypes

ID                           int64
Name                        object
Age                        float64
Profession                  object
salary                       int64
Marriage_proposal_count      int64
dtype: object

### convert datatype

In [58]:
# 
df['Name'] = df['Name'].astype('string')
df.dtypes

ID                                  int64
Name                       string[python]
Age                               float64
Profession                         object
salary                            float64
Marriage_proposal_count             int64
dtype: object

In [59]:
df['salary'] = df['salary'].astype('float')
df.dtypes

ID                                  int64
Name                       string[python]
Age                               float64
Profession                         object
salary                            float64
Marriage_proposal_count             int64
dtype: object

In [60]:
# printing the columns which is having specific datatypes numarical columns
df.select_dtypes(include = ['int','float'])

      ID   Age    salary  Marriage_proposal_count
0      1  23.0  184518.0                        0
1      2  20.0  119572.0                        2
2      3  38.0  174897.0                        1
3      4  56.0  117920.0                        2
4      4  56.0  117920.0                        1
..   ...   ...       ...                      ...
495  496  45.0  137929.0                        0
496  497  46.0   39870.0                        6
497  498  47.0  165951.0                        5
498  499  55.0  192618.0                        5
499  500  59.0  194886.0                       28

[500 rows x 4 columns]

In [61]:
# string columns or catagrical columns
df.select_dtypes(include = ['string','object'])

          Name         Profession
0           AA               hero
1    sophia                 Boxer
2         jake          Scientist
3        vedhu               Chef
4        vedhu               Chef
..         ...                ...
495       John              Boxer
496   Sherlock              Boxer
497   Sherlock          Detective
498     Olivia           Comedian
499   Sherlock  Software Engineer

[500 rows x 2 columns]

In [67]:
# give name of all the columns which are string type 
df.select_dtypes(include = ['string','object']).columns

Index(['Name', 'Profession'], dtype='object')

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       500 non-null    int64
 1   Name                     500 non-null    string
 2   Age                      492 non-null    float64
 3   Profession               500 non-null    object
 4   salary                   500 non-null    float64
 5   Marriage_proposal_count  500 non-null    int64
dtypes: float64(2), int64(2), object(1), string(1)
memory usage: 23.6+ KB

In [74]:
# query: print all the unique profession
df.Profession.unique()

array(['hero', '      Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

In [75]:
# nunique is telling number if unique in this profession 
df.Profession.nunique()

10

In [78]:
# query: how many people are boxer in this dataset
df.Profession.value_counts()

Profession
Chef                 58
Scientist            54
      Boxer          53
Pilot                53
Comedian             52
Software Engineer    51
Doctor               48
hero                 45
Detective            45
Artist               41
Name: count, dtype: int64

In [81]:
# describe statistical information 
# bydefault , describe() works on numerical columns
df.describe()

               ID         Age         salary  Marriage_proposal_count
count  500.000000  492.000000     500.000000                500.00000
mean   250.458000   40.810976  115602.828000                  4.02600
std    144.552978   11.790553   49404.366846                  5.25362
min      1.000000   20.000000   30164.000000                  0.00000
25%    125.750000   31.000000   74964.750000                  1.00000
50%    250.500000   40.500000  117920.000000                  3.00000
75%    375.250000   51.000000  160579.500000                  5.00000
max    500.000000   60.000000  199529.000000                 40.00000

In [84]:
df.describe(include ='int')

               ID  Marriage_proposal_count
count  500.000000                500.00000
mean   250.458000                  4.02600
std    144.552978                  5.25362
min      1.000000                  0.00000
25%    125.750000                  1.00000
50%    250.500000                  3.00000
75%    375.250000                  5.00000
max    500.000000                 40.00000

In [86]:
# describing string/object columns
df.describe(include =['object','string'])

            Name Profession
count        500        500
unique        13         10
top     Sherlock       Chef
freq          61         58

# 4. data flitering and indexing (loc,iloc,where()....)

In [90]:
# fliter all the recordes where salary > 100000
df[df.salary>100000]

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,AA,23.0,hero,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,vedhu,56.0,Chef,117920.0,2
4,4,vedhu,56.0,Chef,117920.0,1
...,...,...,...,...,...,...
493,494,Sophia,39.0,Doctor,174500.0,0
495,496,John,45.0,Boxer,137929.0,0
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,55.0,Comedian,192618.0,5
499,500,Sherlock,59.0,Software Engineer,194886.0,28

In [100]:
# fliter all the records where salary >100000 & salary < 15000000
df[(df.salary < 100000) & (df.salary < 150000)]

Empty DataFrame
Columns: [ID, Name, Age, Profession, salary, Marriage_proposal_count]
Index: []

In [104]:
# query: fliter all the records where salary >100000 /(OR)(salary < 100000
df[(df.salary < 100000) | (df.salary > 150000)]

Empty DataFrame
Columns: [ID, Name, Age, Profession, salary, Marriage_proposal_count]
Index: []

In [115]:
# query: find the person record who is getting highest salary.
# hint :max()
max(df.salary)

148077.0

In [114]:
df.salary.max()

148077.0