# pandas

In [2]:
# def : pandas is a open sourse library  designed for data manipulation and Analysis.
# pandas is designed over the Numpy.

# impotatnt list of operation in Pandas

1. data structure creation (series(1D array),dataframe(2D array))
2. data input and output (csv,excel,sql,json)
3. understading the data set (head,tail,dtype,.....)
4. data flitering and indexing (loc,iloc,where()....)
5. handling of missing values(NaN/Null)
6. removing duplicate values
7. handling inconsistant data
8. data tranformation using apply() and map()
9. Aggregation and grouping
10. Time series operation
11. basic data visualization

# importing and installation of pandas

In [3]:
# 'pip install pandas' this command can create with old numpy version
# 'conda install pandas' this command will update numpy also with pandas. so no issue.
import pandas as  pd

In [4]:
pd.__version__

'2.3.3'

# 1. data structure creation (series(1D array),dataframe(2D array))

### series (1D array)

In [5]:
# create series
ser1 =pd.Series()
print(ser1)

Series([], dtype: object)

In [6]:
# conver list to Series 
list1 = [10,20,30,40,50]
ser2 = pd.Series(list1)
print(ser2)
print(type(ser2))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>

In [7]:
# conver list to Series 
list1 = [10,20,30,40,50,'hello']
ser2 = pd.Series(list1)
print(ser2)
print(type(ser2))
# in pandas strings are represented as object
# imp: in series, all elements have  the same datatype

0       10
1       20
2       30
3       40
4       50
5    hello
dtype: object
<class 'pandas.core.series.Series'>

In [8]:
# example-2: convert tuple to Series
data = (10,20,30,50)
ser3=pd.Series(data)
print(ser3)
print(type(ser3))
print(ser3[2])

# in pandas series direct negative indexing not allowed.

0    10
1    20
2    30
3    50
dtype: int64
<class 'pandas.core.series.Series'>
30

# set cannot be converted to pandas series
# set is unordered and series is ordered, so no conversation
data = {10,20,30,50}
ser3=pd.Series(data)
print(ser3)

In [9]:
# convert the numpy array into series
import numpy as np
arr1 = np.array([10,20,30,40,50])
ser4 = pd.Series(arr1,index=['a','b','c','d','e'])
print(arr1,type(arr1))
print(ser4,type(ser4))
print(ser4['a'])

[10 20 30 40 50] <class 'numpy.ndarray'>
a    10
b    20
c    30
d    40
e    50
dtype: int64 <class 'pandas.core.series.Series'>
10

In [10]:
# update operation on series
ser3[3]=450
# insert new value
ser3[5] = 550
ser3['a'] =650
ser3[60] =750
ser3[1.2] = 950

In [11]:
print(ser3)

0       10
1       20
2       30
3      450
5      550
a      650
60     750
1.2    950
dtype: int64

In [12]:
# delete element form series
ser2 = ser2.drop(1)
ser2

0       10
2       30
3       40
4       50
5    hello
dtype: object

DAY-2

# dataframe(2D array)

In [13]:
# DATA frame is a 2d array,store data in form of matrix.

### creating data frame

In [14]:
import pandas as pd

In [15]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [16]:
# converting list to dataframe
fruits_list = ['aratipandu','mamadipandu','kamalapandu','drakshapandu']
df=pd.DataFrame(fruits_list,columns = ['fruit_name'])
df

     fruit_name
0    aratipandu
1   mamadipandu
2   kamalapandu
3  drakshapandu

In [17]:
# converting 2D list to DataFrame
fruits_list = [['aratipandu',40],['mamadipandu',100],['kamalapandu',20],['drakshapandu',480]]
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price'])
df

     fruit_name  price
0    aratipandu     40
1   mamadipandu    100
2   kamalapandu     20
3  drakshapandu    480

In [18]:
fruits_list = [('aratipandu',40),('mamadipandu',100),('kamalapandu',20),('drakshapandu',480)]
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price'])
df

     fruit_name  price
0    aratipandu     40
1   mamadipandu    100
2   kamalapandu     20
3  drakshapandu    480

In [19]:
# converting 2D list to DataFrame using 3 columns
fruits_list = [['aratipandu',40,10],['mamadipandu',100,90],['kamalapandu',20,5],['drakshapandu',480,120]]
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price','dicount'])
df

     fruit_name  price  dicount
0    aratipandu     40       10
1   mamadipandu    100       90
2   kamalapandu     20        5
3  drakshapandu    480      120

In [20]:
# converting 2D list to DataFrame using 3 columns
fruits_list = {('aratipandu',40,10),('mamadipandu',100,90),('kamalapandu',20,5),('drakshapandu',480,120)}
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price','dicount'])
df

     fruit_name  price  dicount
0   kamalapandu     20        5
1  drakshapandu    480      120
2    aratipandu     40       10
3   mamadipandu    100       90

In [21]:
# creating DataFram from set of tuples
fruits_list = {('aratipandu',40,10),('mamadipandu',100,90),('kamalapandu',20,5),('drakshapandu',480,120)}
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price','dicount'])
df

     fruit_name  price  dicount
0   kamalapandu     20        5
1  drakshapandu    480      120
2    aratipandu     40       10
3   mamadipandu    100       90

# creating DataFram from set of set we cannot create because set is mutable, list is also mutable
# in set we cannot store the mutable items.
# in set only immutable items can store
fruits_list = {{'aratipandu',40,10},{'mamadipandu',100,90},{'kamalapandu',20,5},{'drakshapandu',480,120}}
df=pd.DataFrame(fruits_list,columns = ['fruit_name','price','dicount'])
df

In [22]:
# creating data frame from dictionary
st_data = {'name':['shiva','niranjan','harish','cherry','sai'],'salary':[40,50,60,15,25],'stu_time':[6,4,5,1,3]}
df= pd.DataFrame(st_data)
df

       name  salary  stu_time
0     shiva      40         6
1  niranjan      50         4
2    harish      60         5
3    cherry      15         1
4       sai      25         3

## 2. data input and output (csv,excel,sql,json)

In [23]:
# importing data from csv file 
import os
os.getcwd()
df_csv = pd.read_csv("CSV_data.csv")
df_csv

       Name   Age         Profession  Salary                    Favorite Quote
0      John  25.0  Software Engineer   80000            Keep calm and code on!
1     Alice   NaN             Doctor  120000           Trust me, I'm a doctor!
2     Rocky   NaN              Boxer   50000                 Eye of the tiger!
3  Sherlock  40.0          Detective  150000  It's elementary, my dear Watson.
4  Mr. Bean  50.0           Comedian   10000                   Why so serious?
5  Mr. Bean  50.0           Comedian   10000                   Why so serious?

In [24]:
# import excel file as a DataFrame
df_excel=pd.read_excel("Excel_data.xlsx")
df_excel

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [25]:
# export the  data back to csv  and excel file
df_csv.to_excel("Da22_excel.xlsx",index=False)
df_excel.to_csv("Da22_CSV.csv",index=False)

day-3

In [26]:
df_excel

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [27]:
# reading and writing inn a sql
import sqlite3
# creating a database if it don't exist
conn = sqlite3.connect("shiva_da22.db")

In [28]:
# creating a table and strating the dataframe data inside it
df_excel.to_sql("prof_table",conn,if_exists='replace')

500

In [29]:
# reading the data from sql table to df
df =pd.read_sql('select * from prof_table',conn)
df

,index,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,0,1,olivia,23.0,Teacher,184518,0
1,1,2,sophia,20.0,Boxer,119572,2
2,2,3,jake,38.0,Scientist,174897,1
3,3,4,Rocky,56.0,Chef,117920,2
4,4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...,...
495,495,496,John,45.0,Boxer,137929,0
496,496,497,Sherlock,46.0,Boxer,39870,6
497,497,498,Sherlock,47.0,Detective,165951,5
498,498,499,Olivia,55.0,Comedian,192618,5
499,499,500,Sherlock,59.0,Software Engineer,194886,28

In [30]:
# impoting data from JSON file 
df_json = pd.read_json('json_data.json')
df_json

,order_id,customer_name,food_item,delivery_boy,rating,delivery_time_min
0,101,Ramu,Idli Burger,Speed Shankar,5,15
1,102,Priya,Dosa Pizza,Late Laxman,2,60
2,103,Dinesh,Paneer Sambar,Turbo Thambi,4,25
3,104,Lachu,Mango Maggi,Round Robin,1,90
4,105,Meena,Coconut Coffee,Careless Kannan,3,40

In [31]:
# exporting data from dataframe to json file 
df_json.to_json('food_data.json')

### 3. understading the data set (head,tail,dtype,.....)

In [32]:
# view the data with head(),tail() functions
# head(x) function is used to accessing top x records
# head() by default shows the 5 records
df_excel.head(10)

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1
5   4      Rocky  56.0         Chef  117920                        3
6   4      Rocky  56.0         Chef  117920                       11
7   4      Rocky  56.0         Chef  117920                        2
8   4      Rocky  56.0         Chef  117920                        2
9   4      Rocky  56.0         Chef  117920                        3

In [33]:
# tail(x) function is used to accessing bottom x records
# tail() by default shows the 5 records
df_excel.tail(10)

      ID      Name   Age         Profession  salary  Marriage_proposal_count
490  491      John  57.0              Pilot  154180                        0
491  492      Emma  34.0             Artist  145412                        1
492  493      John  55.0             Artist   57720                        2
493  494    Sophia  39.0             Doctor  174500                        0
494  495     Rocky  27.0             Doctor   46975                        0
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

In [34]:
df_excel.shape

(500, 6)

In [35]:
# shows the single column
df_excel['Name']

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

In [36]:
df_excel.Name

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

In [37]:
df_excel['Profession']

0                Teacher
1                  Boxer
2              Scientist
3                   Chef
4                   Chef
             ...
495                Boxer
496                Boxer
497            Detective
498             Comedian
499    Software Engineer
Name: Profession, Length: 500, dtype: object

In [38]:
df_excel[['Name','Profession']]

          Name         Profession
0       olivia            Teacher
1    sophia                 Boxer
2         jake          Scientist
3        Rocky               Chef
4        Rocky               Chef
..         ...                ...
495       John              Boxer
496   Sherlock              Boxer
497   Sherlock          Detective
498     Olivia           Comedian
499   Sherlock  Software Engineer

[500 rows x 2 columns]

In [39]:
# printing multiple columns
df_excel[['Name','Profession','salary']]

          Name         Profession  salary
0       olivia            Teacher  184518
1    sophia                 Boxer  119572
2         jake          Scientist  174897
3        Rocky               Chef  117920
4        Rocky               Chef  117920
..         ...                ...     ...
495       John              Boxer  137929
496   Sherlock              Boxer   39870
497   Sherlock          Detective  165951
498     Olivia           Comedian  192618
499   Sherlock  Software Engineer  194886

[500 rows x 3 columns]

In [40]:
df_rename=df_excel.rename(columns ={'Name':'peru','Profession':'Vruthi'})
df_rename

      ID       peru   Age             Vruthi  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [41]:
# print all the column names 
df_rename.columns

Index(['ID', 'peru', 'Age', 'Vruthi', 'salary', 'Marriage_proposal_count'], dtype='object')

### creating new column in the dataframe

In [42]:
#  here rank() function is a pandas function
# rank() function is giving rank-1 to minmum salary and higher rank value to higher salary
df_excel['rank'] = df_excel['salary'].rank(ascending =False)
df_excel.sort_values('rank')

# sort_values() is used for sorting  the dataframe based upon a column values

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank
436,437,Sherlock,52.0,Boxer,199529,3,1.0
65,66,Emma,57.0,Pilot,199317,1,2.0
132,133,Rocky,31.0,Doctor,198978,8,3.0
167,168,Mr. Bean,44.0,Comedian,198847,14,4.0
474,475,Sophia,30.0,Doctor,198653,1,5.0
...,...,...,...,...,...,...,...
284,285,Jake,46.0,Detective,30971,1,496.0
329,330,Sherlock,40.0,Scientist,30905,0,497.0
398,399,Rocky,25.0,Scientist,30659,5,498.0
90,91,Rocky,43.0,Software Engineer,30407,10,499.0
213,214,Sherlock,21.0,Chef,30164,2,500.0

In [43]:
# droping the column
# axis =1 : delete the column
# axis =0 : delete the row
df_excel=df_excel.drop(['rank'],axis=1)
df_excel

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

DAY-4

### Replace a value in dataframe

In [44]:
df=df_excel
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [45]:
# repalce all the olivia in name column with cherry
df['Name'] = df.Name.replace('olivia','cherry')
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     cherry  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [46]:
# replacing multiple values
df['Name'] = df.Name.replace({'cherry':'shiva','Rocky':'vedhu'})

# replacing values from multiple columns together
# inplace = true : to perform the task without taking extra space  

df= df.replace({'shiva':'AA','Teacher':'hero'})   # or df.replace({'shiva':'AA','Teacher':'hero'}, inplace  = True)
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1         AA  23.0               hero  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      vedhu  56.0               Chef  117920                        2
4      4      vedhu  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [47]:
# dtypes are used to check the datatype of all the columns
# in pandas, strings are represented with object
df.dtypes

ID                           int64
Name                        object
Age                        float64
Profession                  object
salary                       int64
Marriage_proposal_count      int64
dtype: object

### convert datatype

In [48]:
# 
df['Name'] = df['Name'].astype('string')
df.dtypes

ID                                  int64
Name                       string[python]
Age                               float64
Profession                         object
salary                              int64
Marriage_proposal_count             int64
dtype: object

In [49]:
df['salary'] = df['salary'].astype('float')
df.dtypes

ID                                  int64
Name                       string[python]
Age                               float64
Profession                         object
salary                            float64
Marriage_proposal_count             int64
dtype: object

In [50]:
# printing the columns which is having specific datatypes numarical columns
df.select_dtypes(include = ['int','float'])

      ID   Age    salary  Marriage_proposal_count
0      1  23.0  184518.0                        0
1      2  20.0  119572.0                        2
2      3  38.0  174897.0                        1
3      4  56.0  117920.0                        2
4      4  56.0  117920.0                        1
..   ...   ...       ...                      ...
495  496  45.0  137929.0                        0
496  497  46.0   39870.0                        6
497  498  47.0  165951.0                        5
498  499  55.0  192618.0                        5
499  500  59.0  194886.0                       28

[500 rows x 4 columns]

In [51]:
# string columns or catagrical columns
df.select_dtypes(include = ['string','object'])

          Name         Profession
0           AA               hero
1    sophia                 Boxer
2         jake          Scientist
3        vedhu               Chef
4        vedhu               Chef
..         ...                ...
495       John              Boxer
496   Sherlock              Boxer
497   Sherlock          Detective
498     Olivia           Comedian
499   Sherlock  Software Engineer

[500 rows x 2 columns]

In [52]:
# give name of all the columns which are string type 
df.select_dtypes(include = ['string','object']).columns

Index(['Name', 'Profession'], dtype='object')

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       500 non-null    int64
 1   Name                     500 non-null    string
 2   Age                      492 non-null    float64
 3   Profession               500 non-null    object
 4   salary                   500 non-null    float64
 5   Marriage_proposal_count  500 non-null    int64
dtypes: float64(2), int64(2), object(1), string(1)
memory usage: 23.6+ KB

In [54]:
# query: print all the unique profession
df.Profession.unique()

array(['hero', '      Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

In [55]:
# nunique is telling number if unique in this profession 
df.Profession.nunique()

10

In [56]:
# query: how many people are boxer in this dataset
df.Profession.value_counts()

Profession
Chef                 58
Scientist            54
      Boxer          53
Pilot                53
Comedian             52
Software Engineer    51
Doctor               48
hero                 45
Detective            45
Artist               41
Name: count, dtype: int64

In [57]:
# describe statistical information 
# bydefault , describe() works on numerical columns
df.describe()

               ID         Age         salary  Marriage_proposal_count
count  500.000000  492.000000     500.000000                500.00000
mean   250.458000   40.810976  115602.828000                  4.02600
std    144.552978   11.790553   49404.366846                  5.25362
min      1.000000   20.000000   30164.000000                  0.00000
25%    125.750000   31.000000   74964.750000                  1.00000
50%    250.500000   40.500000  117920.000000                  3.00000
75%    375.250000   51.000000  160579.500000                  5.00000
max    500.000000   60.000000  199529.000000                 40.00000

In [58]:
df.describe(include ='int')

               ID  Marriage_proposal_count
count  500.000000                500.00000
mean   250.458000                  4.02600
std    144.552978                  5.25362
min      1.000000                  0.00000
25%    125.750000                  1.00000
50%    250.500000                  3.00000
75%    375.250000                  5.00000
max    500.000000                 40.00000

In [59]:
# describing string/object columns
df.describe(include =['object','string'])

            Name Profession
count        500        500
unique        13         10
top     Sherlock       Chef
freq          61         58

# 4. data flitering and indexing (loc,iloc,where()....)

In [60]:
# fliter all the recordes where salary > 100000
df[df.salary>100000]

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,AA,23.0,hero,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,vedhu,56.0,Chef,117920.0,2
4,4,vedhu,56.0,Chef,117920.0,1
...,...,...,...,...,...,...
493,494,Sophia,39.0,Doctor,174500.0,0
495,496,John,45.0,Boxer,137929.0,0
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,55.0,Comedian,192618.0,5
499,500,Sherlock,59.0,Software Engineer,194886.0,28

In [61]:
# fliter all the records where salary >100000 & salary < 15000000
df[(df.salary < 100000) & (df.salary < 150000)]

      ID      Name   Age         Profession   salary  Marriage_proposal_count
10    11     vedhu   NaN             Doctor  75543.0                        5
13    14      John  46.0             Artist  43078.0                       12
15    16  Sherlock  30.0              Boxer  57774.0                        0
23    24  Sherlock  42.0              Boxer  92995.0                        2
26    27     Alice  48.0              Pilot  99949.0                        4
..   ...       ...   ...                ...      ...                      ...
488  489      Emma  21.0  Software Engineer  92013.0                        2
489  490      John  56.0          Scientist  41192.0                        7
492  493      John  55.0             Artist  57720.0                        2
494  495     vedhu  27.0             Doctor  46975.0                        0
496  497  Sherlock  46.0              Boxer  39870.0                        6

[196 rows x 6 columns]

In [62]:
# query: fliter all the records where salary >100000 /(OR)(salary < 100000
df[(df.salary < 100000) | (df.salary > 150000)]

      ID      Name   Age         Profession    salary  Marriage_proposal_count
0      1        AA  23.0               hero  184518.0                        0
2      3      jake  38.0          Scientist  174897.0                        1
10    11     vedhu   NaN             Doctor   75543.0                        5
11    12      Jake   NaN             Artist  174780.0                        5
13    14      John  46.0             Artist   43078.0                       12
..   ...       ...   ...                ...       ...                      ...
494  495     vedhu  27.0             Doctor   46975.0                        0
496  497  Sherlock  46.0              Boxer   39870.0                        6
497  498  Sherlock  47.0          Detective  165951.0                        5
498  499    Olivia  55.0           Comedian  192618.0                        5
499  500  Sherlock  59.0  Software Engineer  194886.0                       28

[349 rows x 6 columns]

In [63]:
# query: find the person record who is getting highest salary.
# hint :max()
max(df.salary)

199529.0

DAY-5

In [64]:
# query: find the person record who is getting highest salary.
# hint :max()
df[df.salary == df.salary.max()]

      ID      Name   Age   Profession    salary  Marriage_proposal_count
436  437  Sherlock  52.0        Boxer  199529.0                        3

In [65]:
# query: find the person record who is getting lowest salary.
# hint :min()
df[df.salary == df.salary.min()]

      ID      Name   Age Profession   salary  Marriage_proposal_count
213  214  Sherlock  21.0       Chef  30164.0                        2

In [66]:
# query: print just the name,age,salary of the person having max salary
df[df.salary==df.salary.max()][['Name','Age','salary']]

         Name   Age    salary
436  Sherlock  52.0  199529.0

In [67]:
df[['Name','Age','salary']][df.salary==df.salary.max()]

         Name   Age    salary
436  Sherlock  52.0  199529.0

In [68]:
df[df.salary==df.salary.max()].Name

436    Sherlock
Name: Name, dtype: string

In [69]:
df[['Name','Age','salary']]

          Name   Age    salary
0           AA  23.0  184518.0
1    sophia     20.0  119572.0
2         jake  38.0  174897.0
3        vedhu  56.0  117920.0
4        vedhu  56.0  117920.0
..         ...   ...       ...
495       John  45.0  137929.0
496   Sherlock  46.0   39870.0
497   Sherlock  47.0  165951.0
498     Olivia  55.0  192618.0
499   Sherlock  59.0  194886.0

[500 rows x 3 columns]

In [70]:

df1=df.copy()
df1

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,AA,23.0,hero,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,vedhu,56.0,Chef,117920.0,2
4,4,vedhu,56.0,Chef,117920.0,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929.0,0
496,497,Sherlock,46.0,Boxer,39870.0,6
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,55.0,Comedian,192618.0,5
499,500,Sherlock,59.0,Software Engineer,194886.0,28

In [71]:
### where() : used for flitering the data
# where() function returns Nan in place of thouse values which dont't satisfied the condition
df1=df1.where(df1.Age>50,1)
df1

      ID      Name   Age         Profession    salary  Marriage_proposal_count
0      1         1   1.0                  1       1.0                        1
1      1         1   1.0                  1       1.0                        1
2      1         1   1.0                  1       1.0                        1
3      4     vedhu  56.0               Chef  117920.0                        2
4      4     vedhu  56.0               Chef  117920.0                        1
..   ...       ...   ...                ...       ...                      ...
495    1         1   1.0                  1       1.0                        1
496    1         1   1.0                  1       1.0                        1
497    1         1   1.0                  1       1.0                        1
498  499    Olivia  55.0           Comedian  192618.0                        5
499  500  Sherlock  59.0  Software Engineer  194886.0                       28

[500 rows x 6 columns]

In [72]:
df1=df1.Age.where(df1.Age>50,'a')
df1

0         a
1         a
2         a
3      56.0
4      56.0
       ...
495       a
496       a
497       a
498    55.0
499    59.0
Name: Age, Length: 500, dtype: object

In [73]:
# if you don't want NaN records
df[df.Age>50]

      ID      Name   Age         Profession    salary  Marriage_proposal_count
3      4     vedhu  56.0               Chef  117920.0                        2
4      4     vedhu  56.0               Chef  117920.0                        1
5      4     vedhu  56.0               Chef  117920.0                        3
6      4     vedhu  56.0               Chef  117920.0                       11
7      4     vedhu  56.0               Chef  117920.0                        2
..   ...       ...   ...                ...       ...                      ...
489  490      John  56.0          Scientist   41192.0                        7
490  491      John  57.0              Pilot  154180.0                        0
492  493      John  55.0             Artist   57720.0                        2
498  499    Olivia  55.0           Comedian  192618.0                        5
499  500  Sherlock  59.0  Software Engineer  194886.0                       28

[126 rows x 6 columns]

## indexing: loc & iloc

In [74]:
# loc & iloc  is used for filtering
# these helps to select particular Row & Column in the Dataframe

In [75]:
# query: print records 1 to 4,and columns ID,Name,Age Only
df.loc[1:4,'ID':'Age']   # df.loc[start_row:end_row,col_strat:col_end

   ID       Name   Age
1   2  sophia     20.0
2   3       jake  38.0
3   4      vedhu  56.0
4   4      vedhu  56.0

In [76]:
df.iloc[1:5,0:3]

   ID       Name   Age
1   2  sophia     20.0
2   3       jake  38.0
3   4      vedhu  56.0
4   4      vedhu  56.0

# interview question
Q: what is the difference between loc and iloc?
Ans: 1. in loc columns are passed with there Names but in iloc columns passed as index
2. iloc is easy to use due to index usage 
3. iloc[start_row:end_row-1,col_start: col_end-1]
4. iloc is littel faster than the loc

In [77]:
# query: print records 10 to 40,and columns (Name,Age,profession) Name: ProfessionOnly
df.loc[10:40,'Name':'Profession']

        Name   Age         Profession
10     vedhu   NaN             Doctor
11      Jake   NaN             Artist
12    Olivia  22.0           Comedian
13      John  46.0             Artist
14      Jake  40.0               Chef
15  Sherlock  30.0              Boxer
16      Jake  46.0             Artist
17      Jake  53.0  Software Engineer
18     vedhu  25.0           Comedian
19  Sherlock  40.0          Detective
20  Sherlock  40.0          Detective
21      John  41.0          Scientist
22      John  41.0          Scientist
23  Sherlock  42.0              Boxer
24    Olivia  60.0          Detective
25    Olivia  53.0          Detective
26     Alice  48.0              Pilot
27  Sherlock  55.0          Scientist
28     Alice  21.0               Chef
29     Alice  21.0               Chef
30     Alice  30.0               hero
31    Olivia  30.0             Doctor
32  Mr. Bean  27.0             Artist
33    Olivia  45.0           Comedian
34  Sherlock  46.0               Chef
35  Mr. Bean  44.0           Comedian
36     vedhu  57.0               hero
37  Mr. Bean  32.0          Scientist
38      John  27.0  Software Engineer
39    Olivia  60.0  Software Engineer
40     Alice  52.0               Chef

In [78]:
df.loc[1:5,['Name','Age']]

        Name   Age
1  sophia     20.0
2       jake  38.0
3      vedhu  56.0
4      vedhu  56.0
5      vedhu  56.0

DAY -6

In [79]:
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,AA,23.0,hero,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,vedhu,56.0,Chef,117920.0,2
4,4,vedhu,56.0,Chef,117920.0,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929.0,0
496,497,Sherlock,46.0,Boxer,39870.0,6
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,55.0,Comedian,192618.0,5
499,500,Sherlock,59.0,Software Engineer,194886.0,28

In [80]:
# iloc using the step size
df.iloc[0:200:10, 0:5:2]

      ID   Age    salary
0      1  23.0  184518.0
10    11   NaN   75543.0
20    21  40.0  118998.0
30    31  30.0   77599.0
40    41  52.0   46535.0
50    51  42.0  105830.0
60    61  37.0  106436.0
70    71  40.0  188182.0
80    81  38.0  125743.0
90    91  43.0   30407.0
100  101  60.0  163578.0
110  111  44.0  165346.0
120  121  43.0   34630.0
130  131  26.0  145227.0
140  141  46.0   61653.0
150  151  60.0  135857.0
160  161  42.0  150873.0
170  171  30.0  139649.0
180  181  32.0  134405.0
190  191  34.0  112912.0

In [81]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='object')

In [82]:
# iloc using with specific columns
df.iloc[1:10, [1,3,4]]

        Name   Profession    salary
1  sophia           Boxer  119572.0
2       jake    Scientist  174897.0
3      vedhu         Chef  117920.0
4      vedhu         Chef  117920.0
5      vedhu         Chef  117920.0
6      vedhu         Chef  117920.0
7      vedhu         Chef  117920.0
8      vedhu         Chef  117920.0
9      vedhu         Chef  117920.0

In [83]:
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,AA,23.0,hero,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,vedhu,56.0,Chef,117920.0,2
4,4,vedhu,56.0,Chef,117920.0,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929.0,0
496,497,Sherlock,46.0,Boxer,39870.0,6
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,55.0,Comedian,192618.0,5
499,500,Sherlock,59.0,Software Engineer,194886.0,28

In [84]:
# iloc to get specific value
print(df.iloc[1,5])

2

In [85]:
# loc to get age and salary columns
df.loc[0:5, ["Age", "salary"]]

    Age    salary
0  23.0  184518.0
1  20.0  119572.0
2  38.0  174897.0
3  56.0  117920.0
4  56.0  117920.0
5  56.0  117920.0

In [86]:
# comparison condition inside the loc
# Salary of people Age> 50 & Age < 70
df.loc[(df.Age > 50) & (df.Age < 70), ["Age", "salary"]]

      Age    salary
3    56.0  117920.0
4    56.0  117920.0
5    56.0  117920.0
6    56.0  117920.0
7    56.0  117920.0
..    ...       ...
489  56.0   41192.0
490  57.0  154180.0
492  55.0   57720.0
498  55.0  192618.0
499  59.0  194886.0

[126 rows x 2 columns]

In [87]:
# iloc don't works with pandas Series
# .values will convert it into numpy array
df.iloc[(df.Age > 50).values, 0:4]

      ID      Name   Age         Profession
3      4     vedhu  56.0               Chef
4      4     vedhu  56.0               Chef
5      4     vedhu  56.0               Chef
6      4     vedhu  56.0               Chef
7      4     vedhu  56.0               Chef
..   ...       ...   ...                ...
489  490      John  56.0          Scientist
490  491      John  57.0              Pilot
492  493      John  55.0             Artist
498  499    Olivia  55.0           Comedian
499  500  Sherlock  59.0  Software Engineer

[126 rows x 4 columns]

In [88]:
type((df.Age > 50).values)

numpy.ndarray

In [89]:
### updating a value inside the dataframe

# replace/update all the age > 50 with 18
df.loc[df.Age > 50, "Age"] = 18

In [90]:
df.loc[0,"Name"] = "Rajnikant"
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Rajnikant,23.0,hero,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,vedhu,18.0,Chef,117920.0,2
4,4,vedhu,18.0,Chef,117920.0,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929.0,0
496,497,Sherlock,46.0,Boxer,39870.0,6
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,18.0,Comedian,192618.0,5
499,500,Sherlock,18.0,Software Engineer,194886.0,28

In [91]:
df.iloc[0,1] = "Vikas Babu"
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Vikas Babu,23.0,hero,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,vedhu,18.0,Chef,117920.0,2
4,4,vedhu,18.0,Chef,117920.0,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929.0,0
496,497,Sherlock,46.0,Boxer,39870.0,6
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,18.0,Comedian,192618.0,5
499,500,Sherlock,18.0,Software Engineer,194886.0,28

In [92]:
### at & iat for single value access

# at and iat is faster than loc & iloc

df.at[0, "Name"] = "Mahesh babu"
df.iat[0,1] = "Allu Arjun"
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Allu Arjun,23.0,hero,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,vedhu,18.0,Chef,117920.0,2
4,4,vedhu,18.0,Chef,117920.0,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929.0,0
496,497,Sherlock,46.0,Boxer,39870.0,6
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,18.0,Comedian,192618.0,5
499,500,Sherlock,18.0,Software Engineer,194886.0,28

In [93]:
### sorting rows in a dataframe
df1 = df.sort_values('Name', ascending = False)

In [94]:
# sort_index() is used to sort index of dataframe
df1.sort_index()

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Allu Arjun,23.0,hero,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,vedhu,18.0,Chef,117920.0,2
4,4,vedhu,18.0,Chef,117920.0,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929.0,0
496,497,Sherlock,46.0,Boxer,39870.0,6
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,18.0,Comedian,192618.0,5
499,500,Sherlock,18.0,Software Engineer,194886.0,28

In [95]:
df1.sort_index(inplace = True)
df1

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Allu Arjun,23.0,hero,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,vedhu,18.0,Chef,117920.0,2
4,4,vedhu,18.0,Chef,117920.0,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929.0,0
496,497,Sherlock,46.0,Boxer,39870.0,6
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,18.0,Comedian,192618.0,5
499,500,Sherlock,18.0,Software Engineer,194886.0,28

In [96]:
# used to set a column as a index of dataframe
df1.set_index('ID', inplace = True)

In [97]:
df1.reset_index(inplace = True)
df1

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Allu Arjun,23.0,hero,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,vedhu,18.0,Chef,117920.0,2
4,4,vedhu,18.0,Chef,117920.0,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929.0,0
496,497,Sherlock,46.0,Boxer,39870.0,6
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,18.0,Comedian,192618.0,5
499,500,Sherlock,18.0,Software Engineer,194886.0,28

day-7

# 5. Handling of Missing values(NaN/Null)

In [98]:
# Def: Null/NaN values are missing values. Null is different from 0.
# if their null values in the data then wrong analysis will happen.
# finding the null values in dataframe
import pandas as pd
df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [99]:
# check which column have how many null values
df.isnull().sum()

ID                         0
Name                       0
Age                        8
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [100]:
# records with Null values
df[df.Age.isnull()]

    ID      Name  Age         Profession  salary  Marriage_proposal_count
10  11     Rocky  NaN             Doctor   75543                        5
11  12      Jake  NaN             Artist  174780                        5
45  46      Liam  NaN             Doctor   84583                        0
46  47  Mr. Bean  NaN             Artist  190559                        5
71  72      Emma  NaN              Pilot   49986                        3
72  73    Sophia  NaN             Artist   86741                        1
73  74     Rocky  NaN  Software Engineer  159260                        0
74  75  Sherlock  NaN          Detective  165463                        0

In [101]:
df1 = df.copy()

# delete the records which is having null values
df1 = df1.dropna(axis = 0)
df1

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[492 rows x 6 columns]

In [102]:
df1.shape

(492, 6)

In [103]:
df2 = df.copy()
# delete the column with null value
# how = "any" : if even a single value is null then delete the column
# how = "all" : delete column only if ALL values in the column is NULL
df2 = df2.dropna(axis = 1, how = "any")
df2

      ID       Name         Profession  salary  Marriage_proposal_count
0      1     olivia            Teacher  184518                        0
1      2  sophia                 Boxer  119572                        2
2      3       jake          Scientist  174897                        1
3      4      Rocky               Chef  117920                        2
4      4      Rocky               Chef  117920                        1
..   ...        ...                ...     ...                      ...
495  496       John              Boxer  137929                        0
496  497   Sherlock              Boxer   39870                        6
497  498   Sherlock          Detective  165951                        5
498  499     Olivia           Comedian  192618                        5
499  500   Sherlock  Software Engineer  194886                       28

[500 rows x 5 columns]

In [104]:
# replacing the null values with some other value

df3 = df.copy()

df3.Age = df3.Age.fillna(18)
df3.isnull().sum()

ID                         0
Name                       0
Age                        0
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

# 6. Finding & Handling duplicate values

In [105]:
# in our dataset, name of the columns are inconsistant

# lets make all the column Names start with capital letter
df.columns = df.columns.str.title()

In [106]:
df.columns

Index(['Id', 'Name', 'Age', 'Profession', 'Salary', 'Marriage_Proposal_Count'], dtype='object')

In [107]:
df.Name.unique()

array(['olivia', 'sophia   ', 'jake', 'Rocky', 'Jake', 'Olivia', 'John',
       'Sherlock', 'Alice', 'Mr. Bean', 'Sophia', 'Liam', 'Emma'],
      dtype=object)

In [108]:
df.Name = df.Name.str.title()
df.Name.unique()

array(['Olivia', 'Sophia   ', 'Jake', 'Rocky', 'John', 'Sherlock',
       'Alice', 'Mr. Bean', 'Sophia', 'Liam', 'Emma'], dtype=object)

In [109]:
df.Name = df.Name.str.strip()
df.Name.unique()

array(['Olivia', 'Sophia', 'Jake', 'Rocky', 'John', 'Sherlock', 'Alice',
       'Mr. Bean', 'Liam', 'Emma'], dtype=object)

In [110]:
df.Profession.unique()

array(['Teacher', '      Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

In [111]:
df.Profession = df.Profession.str.strip()

# 8. Data transformation using apply() & map()

In [112]:
# Query: double the salary of the employees

df6 = df.copy()

df6.Salary = df6.Salary.apply(lambda x : x * 2)

In [113]:
df6

      Id      Name   Age         Profession  Salary  Marriage_Proposal_Count
0      1    Olivia  23.0            Teacher  369036                        0
1      2    Sophia  20.0              Boxer  239144                        2
2      3      Jake  38.0          Scientist  349794                        1
3      4     Rocky  56.0               Chef  235840                        2
4      4     Rocky  56.0               Chef  235840                        1
..   ...       ...   ...                ...     ...                      ...
495  496      John  45.0              Boxer  275858                        0
496  497  Sherlock  46.0              Boxer   79740                        6
497  498  Sherlock  47.0          Detective  331902                        5
498  499    Olivia  55.0           Comedian  385236                        5
499  500  Sherlock  59.0  Software Engineer  389772                       28

[500 rows x 6 columns]

In [114]:
# Query-2: create a new column which divide the employees as senior and junior
# based upon the salary. if salary > 300000 : Senior otherwise Junior

# use of apply() on complete dataframe
df6['category'] = df6.apply(lambda row : 'OLD' if row['Age'] > 40 else 'Young', axis = 1)
df6

,Id,Name,Age,Profession,Salary,Marriage_Proposal_Count,category
0,1,Olivia,23.0,Teacher,369036,0,Young
1,2,Sophia,20.0,Boxer,239144,2,Young
2,3,Jake,38.0,Scientist,349794,1,Young
3,4,Rocky,56.0,Chef,235840,2,OLD
4,4,Rocky,56.0,Chef,235840,1,OLD
...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,275858,0,OLD
496,497,Sherlock,46.0,Boxer,79740,6,OLD
497,498,Sherlock,47.0,Detective,331902,5,OLD
498,499,Olivia,55.0,Comedian,385236,5,OLD
499,500,Sherlock,59.0,Software Engineer,389772,28,OLD

day-8

In [115]:
# Example-3: Apply() function
# Query: create a new column which is having salary/age
# Motive: use of apply() function on complete dataframe and access multiple columns

df6["Salary_per_year_age"] = df6.apply(lambda row : row['Salary'] / row['Age'], axis = 1)
df6

,Id,Name,Age,Profession,Salary,Marriage_Proposal_Count,category,Salary_per_year_age
0,1,Olivia,23.0,Teacher,369036,0,Young,16045.043478
1,2,Sophia,20.0,Boxer,239144,2,Young,11957.200000
2,3,Jake,38.0,Scientist,349794,1,Young,9205.105263
3,4,Rocky,56.0,Chef,235840,2,OLD,4211.428571
4,4,Rocky,56.0,Chef,235840,1,OLD,4211.428571
...,...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,275858,0,OLD,6130.177778
496,497,Sherlock,46.0,Boxer,79740,6,OLD,1733.478261
497,498,Sherlock,47.0,Detective,331902,5,OLD,7061.744681
498,499,Olivia,55.0,Comedian,385236,5,OLD,7004.290909
499,500,Sherlock,59.0,Software Engineer,389772,28,OLD,6606.305085

## map()

In [116]:
# def: map() is used for element-wise transformation just like apply()

# example-1
df7 = df.copy()

# Query: convert all the strings in upper case
df7.Name = df7.Name.map(lambda val : str(val).upper())
df7

      Id      Name   Age         Profession  Salary  Marriage_Proposal_Count
0      1    OLIVIA  23.0            Teacher  184518                        0
1      2    SOPHIA  20.0              Boxer  119572                        2
2      3      JAKE  38.0          Scientist  174897                        1
3      4     ROCKY  56.0               Chef  117920                        2
4      4     ROCKY  56.0               Chef  117920                        1
..   ...       ...   ...                ...     ...                      ...
495  496      JOHN  45.0              Boxer  137929                        0
496  497  SHERLOCK  46.0              Boxer   39870                        6
497  498  SHERLOCK  47.0          Detective  165951                        5
498  499    OLIVIA  55.0           Comedian  192618                        5
499  500  SHERLOCK  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [117]:
# Example-2

# Query: convert professions from english language to Telegu
df.Profession.unique()

array(['Teacher', 'Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

In [118]:
profession_map = {
    'Teacher' : 'Saarr',
    'Boxer' : 'Pedi',
    'Scientist' : 'sastravedu',
    'Chef' : 'Onetavadu',
    'Doctor' : 'Vaitedu',
    'Artist' : 'kalakar',
    'Comedian' : 'Haasya',
    'Software Engineer' : 'kuludu',
    'Detective' : 'Guptachariya',
    'Pilot' : 'Galodu'
}

df7['Prof_telegu'] = df7.Profession.map(profession_map)
df7

,Id,Name,Age,Profession,Salary,Marriage_Proposal_Count,Prof_telegu
0,1,OLIVIA,23.0,Teacher,184518,0,Saarr
1,2,SOPHIA,20.0,Boxer,119572,2,Pedi
2,3,JAKE,38.0,Scientist,174897,1,sastravedu
3,4,ROCKY,56.0,Chef,117920,2,Onetavadu
4,4,ROCKY,56.0,Chef,117920,1,Onetavadu
...,...,...,...,...,...,...,...
495,496,JOHN,45.0,Boxer,137929,0,Pedi
496,497,SHERLOCK,46.0,Boxer,39870,6,Pedi
497,498,SHERLOCK,47.0,Detective,165951,5,Guptachariya
498,499,OLIVIA,55.0,Comedian,192618,5,Haasya
499,500,SHERLOCK,59.0,Software Engineer,194886,28,kuludu

# 9. Aggregation and Grouping

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Id                       500 non-null    int64
 1   Name                     500 non-null    object
 2   Age                      492 non-null    float64
 3   Profession               500 non-null    object
 4   Salary                   500 non-null    int64
 5   Marriage_Proposal_Count  500 non-null    int64
dtypes: float64(1), int64(3), object(2)
memory usage: 23.6+ KB

In [120]:
# total salary
df.Salary.sum()

np.int64(57801414)

In [121]:
# average salary
df.Salary.mean()

np.float64(115602.828)

In [122]:
# median of salary
# middle value after sorting data
# 10, 20, 30, 40, 50, 60, 70, 80

df.Salary.median()

117920.0

In [123]:
# mode() : most frequent data
df.Profession.mode()

0    Chef
Name: Profession, dtype: object

In [124]:
# minimum salary : min()
df.Salary.min()

30164

In [125]:
# maximum salary : max()
df.Salary.max()

199529

In [126]:
# mode() : most frequent data
df.Profession.mode()

0    Chef
Name: Profession, dtype: object

In [127]:
# value_counts() : number of records related to particular category
df.Profession.value_counts()

Profession
Chef                 58
Scientist            54
Boxer                53
Pilot                53
Comedian             52
Software Engineer    51
Doctor               48
Teacher              45
Detective            45
Artist               41
Name: count, dtype: int64

In [128]:
# count() : count the Non-NULL values
df.count()

Id                         500
Name                       500
Age                        492
Profession                 500
Salary                     500
Marriage_Proposal_Count    500
dtype: int64

In [129]:
df.isnull().sum()

Id                         0
Name                       0
Age                        8
Profession                 0
Salary                     0
Marriage_Proposal_Count    0
dtype: int64

In [130]:
# groupby() : group the data based upon category

df.groupby('Profession').Name.count()

Profession
Artist               41
Boxer                53
Chef                 58
Comedian             52
Detective            45
Doctor               48
Pilot                53
Scientist            54
Software Engineer    51
Teacher              45
Name: Name, dtype: int64

In [131]:
# find average salary based upon profession
df.groupby('Age').Salary.mean()

Age
20.0    107930.300000
21.0    111202.666667
22.0    123330.000000
23.0    106353.875000
24.0     96071.000000
25.0    118117.956522
26.0    105049.545455
27.0    121657.000000
28.0    115759.727273
29.0    106755.333333
30.0    126964.785714
31.0    142756.833333
32.0    126444.230769
33.0    130019.428571
34.0    114673.000000
35.0     78758.000000
36.0    124278.777778
37.0    113419.230769
38.0    137063.000000
39.0    103876.769231
40.0    108059.400000
41.0    120925.900000
42.0    106310.411765
43.0     94403.111111
44.0    126647.916667
45.0    127032.428571
46.0     96160.705882
47.0    106546.000000
48.0    113052.785714
49.0    117906.090909
50.0    130377.857143
51.0    115272.333333
52.0    141711.333333
53.0     99333.500000
54.0    129167.846154
55.0    122092.700000
56.0     97167.714286
57.0    125854.052632
58.0    111681.090909
59.0    115163.000000
60.0    114066.666667
Name: Salary, dtype: float64

In [132]:
# agg() : can apply mutliple aggregate function together on data

df[["Age", "Salary"]].agg(["mean", "sum", "min", "max" ])

               Age        Salary
mean     40.810976  1.156028e+05
sum   20079.000000  5.780141e+07
min      20.000000  3.016400e+04
max      60.000000  1.995290e+05

In [133]:
# apply different aggregate functions on different columns
df.agg({
    "Age" : ["min", "max"],
    "Salary":["mean", "min"]
})

       Age      Salary
min   20.0   30164.000
max   60.0         NaN
mean   NaN  115602.828

In [134]:
# groubpy() + agg()
df.groupby("Profession").agg({
    "Age" : ["min", "max"],
    "Salary":["mean", "min"]
})

                    Age               Salary
                    min   max           mean    min
Profession
Artist             20.0  60.0  124550.756098  32961
Boxer              20.0  58.0  103895.867925  30976
Chef               20.0  60.0  110806.620690  30164
Comedian           20.0  60.0  122689.000000  32354
Detective          20.0  60.0  120964.977778  30971
Doctor             22.0  60.0  113964.333333  31209
Pilot              20.0  60.0  108641.471698  31129
Scientist          22.0  60.0  126669.481481  30659
Software Engineer  21.0  60.0  117908.941176  30407
Teacher            20.0  60.0  107922.711111  31162

day-9

## Merge two dataframes

In [135]:
import pandas as pd
# Def: Merge two dataframes based upon common column.
# functions used for merging dataframes : merge(), join(), concat()
# merge() function
df1 = pd.DataFrame({'ID' : [1,2,3], 'DreamCompany' : ["Google", "Nvidia", "Accenture"], "Role" : ["DA", "DS", "TL"]})
df2 = pd.DataFrame({"ID" : [2,3,4], 'DreamPackage' : [20, 24, 50]})
print(df1)
print(df2)

   ID DreamCompany Role
0   1       Google   DA
1   2       Nvidia   DS
2   3    Accenture   TL
   ID  DreamPackage
0   2            20
1   3            24
2   4            50

In [136]:
# Merge() function behaves like joins in SQL
# by deafult, merge() function perform inner join like operation
# inner merge : common records from both the data frames
merge_df = pd.merge(df1, df2, on = "ID")
merge_df

   ID DreamCompany Role  DreamPackage
0   2       Nvidia   DS            20
1   3    Accenture   TL            24

In [137]:
merge_df = pd.merge(df1, df2, on = "ID", how = "inner")
merge_df

   ID DreamCompany Role  DreamPackage
0   2       Nvidia   DS            20
1   3    Accenture   TL            24

In [138]:
# left merge : Pick all records from Left table and common records from the Right table
merge_df = pd.merge(df1, df2, on = "ID", how = "left")
merge_df

   ID DreamCompany Role  DreamPackage
0   1       Google   DA           NaN
1   2       Nvidia   DS          20.0
2   3    Accenture   TL          24.0

In [139]:
# right merge : Pick all records from right table and common records from the left table
merge_df = pd.merge(df1, df2, on = "ID", how = "right")
merge_df

   ID DreamCompany Role  DreamPackage
0   2       Nvidia   DS            20
1   3    Accenture   TL            24
2   4          NaN  NaN            50

In [140]:
# outer merge : Pick all records from right table and left table
# common records will be consider one time only
merge_df = pd.merge(df1, df2, on = "ID", how = "outer")
merge_df

   ID DreamCompany Role  DreamPackage
0   1       Google   DA           NaN
1   2       Nvidia   DS          20.0
2   3    Accenture   TL          24.0
3   4          NaN  NaN          50.0

## join()

In [141]:
# used to join mainly based upon the index value
df3 = pd.DataFrame({"Name_richest" : ["Ambani", "Elon", "Niranjan", "Larry"]}, index = [10,20,30,40])
df4 = pd.DataFrame({"Networth" : [10, 15, 500, 2]}, index = [20, 30, 40, 50])

joined_df = df3.join(df4, how = "inner")
joined_df

   Name_richest  Networth
20         Elon        10
30     Niranjan        15
40        Larry       500

In [142]:
joined_df = df3.join(df4, how = "left")
joined_df

   Name_richest  Networth
10       Ambani       NaN
20         Elon      10.0
30     Niranjan      15.0
40        Larry     500.0

In [143]:
joined_df = df3.join(df4, how = "right")
joined_df

   Name_richest  Networth
20         Elon        10
30     Niranjan        15
40        Larry       500
50          NaN         2

In [144]:
joined_df = df3.join(df4, how = "outer")
joined_df

   Name_richest  Networth
10       Ambani       NaN
20         Elon      10.0
30     Niranjan      15.0
40        Larry     500.0
50          NaN       2.0

## concat()

In [145]:
# Concat() merge the dataframes vertically and horizontally
# axis = 0 -> concatinating Vertically ( increase the ROWS)
# axis = 1 -> concatinating Horizontally (add Columns)
df5 = pd.DataFrame({"ID" : [1,2], "Movie" : ["kobbari matta", "Paradise"]})
df6 = pd.DataFrame({"ID" : [3,4], "Movie" : ["Titanic", "spiderman"]})
df7 = pd.DataFrame({"ID" : [5,6], "Movie" : ["Dhurander", "Kalank"]})

concat_df = pd.concat([df5, df6, df7], axis = 0, ignore_index = True)
concat_df

   ID          Movie
0   1  kobbari matta
1   2       Paradise
2   3        Titanic
3   4      spiderman
4   5      Dhurander
5   6         Kalank